const question = document.getElementById("question");
const button = document.getElementById("button");
const loading = document.getElementById("loading");

var lastQuestion = 0;

const questionList = [
  "If you could have any superpower, what should it be and why?",
  "Have you ever broken the law?",
  "What would you do if you won the lottery?",
  "What was your worst date ever?",
  "If you won the lottery, would you keep working in your current profession?",
  "How did you meet your best friend?",
  "How much time do you spend with your family?",
  "Are people better at creating things or destroying things?",
  "Do you think you could live in another country?",
  "Who do you consider as family?",
  "What have you been most proud of learning lately?",
  "Do you find purpose in your life?",
  "What kind of goals do you have for the next year?",
  "Which is more important: the human body or the human mind?",
  "What weird or useless talent do you have?",
  "What is the most useful thing you own?",
  "Who had the biggest impact on the person you have become?",
  "What would be your perfect weekend?",
  "How are you really doing?",
  "When was the last time you did something for the first time?",
  "What are your current priorities in this season of your life, and why?",
  "How would you like people to experience you? What kind of person do you want to be in the world?",
  "If you had a whole day where you could do anything you wanted, what would you do?",
  "What are you most proud of about yourself?",
  "What is your greatest accomplishment?",
  "What are you still hoping to accomplish?",
  "What do you want people to know about you?",
  "What do you need more of in your life?",
  "What do you need less of in your life?",
  "What do you feel has been your greatest 'win' so far in your life?",
  "What three words describe what you’re most grateful for?",
  "Would you rather people perceive you as being kind, smart, or attractive?",
  "How do you like to receive care?",
  "How do you cope when things get hard?",
  "What do you really care about?",
  "What really frustrates you?",
  "What keeps you up at night?",
  "How did you feel about where you grew up? Was it a supportive environment?",
  "Who are you most like in your family?",
  "Who in your family do you struggle with?",
  "Is there a time when you did something that seems so out of character that most people wouldn’t believe it?",
  "What is the most trouble you’ve ever been in?",
  "What values are most important to you?",
  "If one wish of yours could come true, what would it be?",
  "If you could travel anywhere, where would you go?",
  "If you could meet anyone in the world, alive or deceased, who would it be?",
  "What brings you joy?",
  "What is the best piece of advice you've ever been given?",
  "What movie or show do you keep rewatching?",
  "What was your favorite game as a child?",
  "Which book or movie impacted you most growing up?",
  "What’s your favorite childhood memory?",
  "What is your favorite memory?",
  "How do you know when you can trust someone?",
  "What event has had a large impact on your life?",
  "If you lost a loved one, do you think you would come to me for support?",
  "If you lost your job, would you come to me for help?",
  "Have you ever stopped talking to a friend?",
  "Has a friend ever stopped talking to you?",
  "What do you find most challenging in your life right now?",
  "What is something that not many people know about you?",
  "What prevents you from sharing that part of yourself?",
  "Are you a morning or night person?",
  "What is the first thing you do when you get up in the morning?",
  "What would you do with your 15 minutes of fame?",
  "Where is the one place in the world you feel safe?",
  "Everyone has a mission in life. What do you think your mission is?",
  "Describe yourself in 3 words.",
  "If a crystal ball could tell you the truth about yourself, your life, the future, or anything else, what would you want to know?",
  "Is there something that you’ve dreamed of doing for a long time? Why haven’t you done it?",
  "What is the greatest accomplishment of your life?",
  "What do you value most in a friendship?",
  "What is your most treasured memory?",
  "What is your most terrible memory?",
  "If you knew that in one year you would die suddenly, would you change anything about the way you are now living? Why?",
  "What does friendship mean to you?",
  "What roles do love and affection play in your life?",
  "Share something you consider to be a positive characteristic of your partner. Share a total of five items.",
  "How close and warm is your family? Do you feel your childhood was happier than most other people’s?",
  "How do you feel about your relationship with your mother?",
  "Given the choice of anyone in the world, whom would you want as a dinner guest?",
  "Would you like to be famous? In what way?",
  "Before making a telephone call, do you ever rehearse what you are going to say? Why?",
  "What would constitute a 'perfect' day for you?",
  "When did you last sing to yourself? To someone else?",
  "If you were able to live to the age of 90 and retain either the mind or body of a 30-year-old for the last 60 years of your life, which would you want?",
  "Do you have a secret hunch about how you will die?",
  "Name three things you and your partner appear to have in common.",
  "For what in your life do you feel most grateful?",
  "If you could change anything about the way you were raised, what would it be?",
  "Take four minutes and tell your partner your life story in as much detail as possible.",
  "If you could wake up tomorrow having gained any one quality or ability, what would it be?",
  "If you could have three wishes, what would they be?",
  "Who was your favorite cartoon character when you were a kid?",
  "What does spirituality mean to you?",
  "Do you believe in giving people second chances, and why?",
  "How would you describe your first crush?",
  "What are your favorite hobbies?",
  "What is your star sign? And do you believe in astrology?",
  "What do you want people to remember about you after you’re gone?",
  "What was the most important lesson you’ve learned from a past relationship?",
  "What are some of your favorite books?",
  "Do you think anyone has the capacity to cheat or do you think only cheaters cheat?",
  "Have you ever shoplifted anything?",
  "Have you ever told a lie that you regretted?",
  "Have you ever done something you regretted?",
  "Do you ever make excuses for your bad behavior? (e.g., I punched him because he was a jerk.)",
  "What is your favorite workout?",
  "How do you think you'd be different if you were raised in a different family?",
  "What is the most important lesson you've learned this year?",
  "What superpowers did you wish you had when you were a kid?",
  "What did you want to be when you grew up?",
  "Are you a mountain or a beach person?",
  "Are you very close to anyone in your family? Why?",
  "Have you ever had your heart broken? What did it feel like to you?",
  "Are you still friends with anyone from high school?",
  "What was your favorite subject or class in high school?",
  "What was the most memorable experience from your childhood?",
  "How do you relax when you're stressed out?",
  "What is a skill that you want to build?",
  "If you could change one decision you made when you were younger what would it be and why?",
  "If you could change one thing about your childhood what would it be and why?",
  "Do you know how to play any musical instruments?",
  "Who or what inspires you?",
  "What is your place in the whole world?",
  "Is there anything from the 1980s that you wish would come back?",
  "Do you get déjà vu? What does it feel like for you?",
  "What makes you feel nostalgic?",
  "What would you do if you found out you had a year to live?",
  "What would you do if you found out you had a year to live?",
  "If you redesigned society, what would you change?",
  "What would be a perfect day for you?",
  "What impresses you?",
  "If you had to eat only one meal for the rest of your life what would it be?",
  "What's your least favorite food?",
  "What's one thing I don't already know about you?",
  "Do you believe in soul mates?",
  "What is your love language?",
  "Do you want to have kids?",
  "How do you imagine your life in 10 years? 20 years? 50 years?",
  "If you had all the money you needed, what would you do with your life?",
  "How do you react when you're upset?",
  "If you had a partner who gained a lot of weight, would you stay with them?",
  "What do you think leads people to cheat in relationships?",
  "If you were having relationship troubles, would you ever go see a relationship counselor?",
  "What's one time when you had to compromise? How did that feel to you?",
  "What would be the perfect amount of time each day that you'd spend with your partner?",
  "What’s a deal-breaker for you in a relationship?",
  "If you could magically change one thing in your life, what would it be?",
  "If you could magically change one thing in your life, what would it be?",
  "What do you think of mindfulness?",
  "Do you think we’d be better off without social media?",
  "What do you think it means to be healthy?",
  "What do you love the most in life?",
  "Do you vote?",
  "Do you believe in karma?",
  "What do you think about freedom of speech?",
  "Do you think there is an afterlife of any kind?",
  "What do you think about veganism?",
  "What do you think about the current younger generation?",
  "Do you think bullies see themselves as bullies?",
  "Do you tend to have trust issues?",
  "Do you feel like men and women are equal?",
  "Do you think people can change?",
  "What's your favorite activity to do with friends?",
  "What's one thing you believe in that's kinda weird?",
  "Where is your favorite place to go eat?",
  "What was one of your funniest moments?",
  "If I asked you, 'Who are you?' How would you answer?",
  "Do you respect yourself?",
  "Are you confident? Why or why not?",
  "Do you like who you are?",
  "How do you express your emotions?",
  "What makes you happy?",
  "What are your strengths and weaknesses?",
  "Do you forgive those who have hurt you? How?",
  "Do you think you're brave? Why or why not?",
  "How do you engage in self-care?",
  "Do you try to grow and improve your abilities?",
  "Are you proud of yourself?",
  "Do you know what you want in life?",
  "In what ways do you think positively? negatively?",
  "What's your personal mission statement?",
  "Do you believe you can manifest your dreams?",
  "What are your long-term goals?",
  "What are you thankful for?",
  "Do you love yourself?",
  "What are your core values?",
  "Do you consider yourself an introvert, extrovert, or somewhere in the middle?",
  "What motivates you?",
  "How do you respond to rejection?",
  "Do you ever feel shame or guilt? What causes it?",
  "Do you suppress or express your emotions? Why and how?",
  "Are you generally present in the moment or do you spend a lot of time in your head?",
  "Do you have a healthy relationship with your smartphone?",
  "What makes you feel vulnerable?",
  "What are your good habits and bad habits?",
  "What is your true calling?",
  "What makes you feel empowered? Disempowered?",
  "What anti-stress strategies help you most?",
  "Do you ever have FOMO (Fear of Missing Out)?",
  "Do you have an easy or hard time letting go of the past?",
  "How do you self-soothe when you're upset?",
  "Do you tend to have a scarcity mindset or an abundance mindset?",
  "What's your communication style?",
  "Do you practice random acts of kindness?",
  "What is your best life?",
  "What makes you jealous or envious?",
  "Have you ever faked happiness?",
  "How secure or insecure do you tend to be in relationships?",
  "Do you tend to be an optimist or a pessimist?",
  "How positive are you about your body?",
  "Have you ever cheated emotionally?",
  "What are your highest aspirations?",
  "What negative thoughts do you have? How might you shift them to be more positive?",
  "Have you ever been in a toxic relationship?",
  "What makes you laugh?",
  "How many hugs do you need each day?",
  "What brings you the most joy?",
  "What is the most difficult thing you've ever apologized for?",
  "How do you define work-life balance?",
  "What is one thing that gives you a sense of awe?",
  "Have you ever lost yourself? If so, how did you find yourself again?",
  "Have you ever felt helpless or hopeless? What happened?",
  "What gives you a sense of inner peace?",
  "What makes you feel overwhelmed?",
  "Have you ever been passive-aggressive?",
  "Would you say that you're hopeful?",
  "What is one mistake you made that you learned something from?",
  "Do you procrastinate?",
  "What is your favorite way to be more productive?",
  "Do you listen to your intuition?",
  "What is your go-to topic for small talk?",
  "Have you ever done a 30-day challenge?",
  "Have you ever done shadow work?",
  "Have you ever tried float therapy?",
  "Do you know yourself? How do you know who you are?",
  "Do you know what the difference is between your wants and your needs?",
  "Do you tend to be intrinsically motivated or extrinsically motivated?",
  "What triggers you?",
  "Have you ever been to therapy? What did or didn't you like about it?",
  "Would you consider yourself an extrovert or introvert?",
  "Has anyone ever guilt-tripped you?",
  "Are you a people-pleaser?",
  "What was the most difficult conversation you ever had?",
  "Have you ever tried the carnivore diet? Or have you ever tried a vegan diet?",
  "What is your biggest fear?",
  "What is your greatest accomplishment? Why are you proud of it?",
  "If you could change one thing about your past, what would it be?",
  "What do you consider your greatest strength and weakness?",
  "How do you handle stress or difficult situations?",
  "What are some habits you’re trying to break?",
  "Are there any skills you’re currently working to develop?",
  "How have you evolved as a person since the Covid-19 pandemic?",
  "Do you think the Covid-19 pandemic affected you? Why or why not?",
  "What is the defining moment in your life that shaped who you are today?",
  "If you could have any superpower, what power would best help you achieve your dreams?",
  "How do you define success, and do you feel you’re on your way to achieving it?",
  "In what ways do you practice self-care and maintain mental well-being?",
  "What motivates you to keep going during tough times?",
  "Which of your school teachers had the biggest effect on who you are today? Were they your favorite teacher?",
  "What does personal growth mean to you, and how do you actively pursue it?",
  "How do you approach setting and working toward personal goals?",
  "When faced with criticism, how do you react and learn from it?",
  "Are you an introvert or an extrovert? Do you like what you are?",
  "What have you always wanted to learn or try but haven’t yet?",
  "How do you maintain a healthy work/life balance?",
  "Who is someone you’d like to be more like?",
  "Are there any bad habits that you’re trying to kick?",
  "When was the last time you really unplugged from it all?",
  "What is your favorite childhood memory?",
  "How do you stay true to yourself when faced with external pressures or expectations?",
  "In what ways do you step out of your comfort zone to grow as a person?",
  "What was a major change for you, how did you cope, and how did it affect the rest of your life?",
  "How is your mental health these days? What are you doing to improve or maintain it?",
  "If you could only bring three items with you on a deserted island, what would they be and why?",
  "What role does self-reflection play in your everyday life, and how do you practice it?",
  "How do you feel like you maintain a sense of purpose and direction in your life?",
  "How would you define the perfect life?",
  "If you could achieve anything within the next five years, what would it be?",
  "What steps are you actively taking to reach your goals?",
  "What long-term goal have you set for yourself, and how do you plan to make it happen?",
  "If you could have your dream job and money wasn’t an issue, what would it be and why?",
  "What are some short-term goals you’re currently working towards?",
  "How do you stay motivated and focused on your aspirations?",
  "Did a specific person or event inspire your goals?",
  "Have your goals and aspirations changed over time? If so, how and why?",
  "What motivates you to get out of bed every day?",
  "What resources or support do you feel you need to achieve your dreams?",
  "How do you measure your progress toward your goals, and how do you celebrate your achievements?",
  "Are there any fears or challenges holding you back from pursuing your dreams? How do you plan to overcome them?",
  "How do you balance pursuing your dreams with other aspects of your life, such as relationships, work, and personal well-being?",
  "How do you prioritize your goals when faced with competing interests or limited time?",
  "What is the biggest thing holding you back right now?",
  "What is a dream or goal that you’ve had since childhood? Are you still working towards it?",
  "If you had unlimited resources, what would you do? Work? Travel? Etc.",
  "How do you handle setbacks or obstacles while working toward your goals?",
  "What has been your most significant achievement in pursuing your dreams so far?",
  "Do you need a plan or roadmap for achieving your aspirations? Or do you go with the flow?",
  "Do you have any mentors? If so, how do you seek guidance or mentorship to help you reach your goals?",
  "How do you stay adaptable and open to change as you work towards your aspirations?",
  "Have you ever had to let go of a dream or goal? If so, why and how did you cope with that decision?",
  "How do you ensure your goals align with your values and contribute to your happiness and well-being?",
  "If a genie gave you three wishes, what would they be?",
  "What are the core values you believe in and try to follow?",
  "How do your beliefs or religion shape your actions and decisions?",
  "Are you religious? Why or why not?",
  "Have you ever questioned or changed your beliefs? Why?",
  "How has your upbringing shaped what you believe in today?",
  "Can you share an experience that significantly impacted your beliefs?",
  "How do you handle situations where your values conflict with those of others?",
  "In what ways do your values influence your personal and professional relationships?",
  "What role do your beliefs play in your overall sense of identity?",
  "Did your favorite book or movie influence your worldview?",
  "What effect did family members have on your current beliefs?",
  "How important is it for you to surround yourself with people who share similar values and beliefs?",
  "Have your values or beliefs ever been challenged? How did you respond to that challenge?",
  "How do you strive to live in alignment with your values daily?",
  "Are there any values you’ve adopted from other cultures or traditions that resonate with you?",
  "Do you have any beliefs that directly contradict social norms?",
  "Is it important for you to engage in self-reflection and introspection to examine your values and beliefs?",
  "In what ways do you actively work to broaden your understanding of different belief systems or perspectives?",
  "What role do your values and beliefs play in your decision-making process?",
  "Can you think of a time when your values or beliefs positively impacted someone else’s life?",
  "How do you navigate situations where your values may be at odds with your professional obligations?",
  "How have your values and beliefs evolved, and what factors have contributed to those changes?",
  "What qualities do you value most in a friend or significant other?",
  "How do you handle conflict in relationships?",
  "What has been your most challenging experience in a relationship, and what did you learn from it?",
  "How do you balance time between your friends and your relationship?",
  "What is your love language? Do you understand your partner’s love language?",
  "Can you share an experience that strengthened a bond with someone in your life?",
  "What role does trust play in your relationships, and how do you build and maintain it?",
  "How important is open and honest communication in your connections with others?",
  "What’s your biggest regret in a past romantic relationship?",
  "How do you balance your personal needs and boundaries with the needs of your relationships?",
  "What are some strategies you use to resolve misunderstandings or disagreements with loved ones?",
  "How do you handle and cope with a breakup?",
  "Who is your best friend, and why?",
  "How do you approach finding a partner?",
  "Do you enjoy small talk, or do you prefer to get to the deep stuff quickly?",
  "What do you do to connect on a deeper level with people?",
  "How have your past relationships influenced your approach to current and future partners?",
  "What are your favorite things to do on a first date?",
  "How do you handle relationship stress or external pressures that may impact your connections with others?",
  "What role does empathy play in your relationships, and how do you practice it?",
  "Do you believe in soulmates?",
  "What is your biggest pet peeve that you can’t get over in a potential friend?",
  "How important is it for you to maintain a diverse group of friends or connections with different perspectives?",
  "In what ways do you support and encourage the personal growth of those close to you?",
  "What does being a good friend look like to you?",
  "How do you recognize when a relationship is no longer serving you or the other person positively?",
  "What is a deal breaker for you when looking for a partner?",
  "Have you ever had a long-distance relationship? If so, how did it go?",
  "In what ways do you seek to improve your relationship skills and understanding of others’ needs?",
  "What defines close friends to you?",
  "How has your approach to relationships and connections evolved, and what factors contributed to these changes?",
  "What role does social media play in your relationships?",
  "If you had to ask your best friend to describe you in three words, what would they say?",
  "What has been the most transformative experience in your life?",
  "Do you believe in second chances? Is it different for you vs. other people?",
  "What was your biggest failure, and how did you grow from it?",
  "If you could share one piece of advice with your younger self, what would it be?",
  "What coping mechanisms do you rely on during a challenging time?",
  "In what ways has your most significant failure shaped your perspective on success and personal growth?",
  "Who are the people you lean on during big life changes?",
  "How have your relationships been affected by these pivotal moments in your life? Either romantic or not.",
  "If you could go back in time, would you change anything about a difficult experience? Why or why not?",
  "How do you plan to use the advice you would give your younger self to guide your future actions and decisions?",
  "Can you share an experience that taught you an important lesson about life?",
  "How do you apply the wisdom gained from your life experiences to your personal and professional endeavors?",
  "What is the most valuable piece of advice someone has ever given you, and how has it impacted your life?",
  "How do you approach new challenges or opportunities with the lessons you’ve learned from past experiences?",
  "Can you recall when you had to step out of your comfort zone? What did you learn from that experience?",
  "What TV show character do you feel most similar to, and why?",
  "In what ways do you share the lessons you’ve learned with others, such as friends, family, or colleagues?",
  "What’s the weirdest thing or unexplainable experience that has happened to you?",
  "How do you maintain a growth mindset and continue to learn from your positive and negative experiences?",
  "What is your favorite place to visit, and what meaning does it hold for you?",
];

console.log(questionList.length);

button.addEventListener("click", () => {
  question.innerText = "";
  question.classList.remove("display");
  loading.style.display = "block";

  setTimeout(() => {
    loading.style.display = "none";
    randomindex = Math.floor(Math.random() * questionList.length);
    while (randomindex == lastQuestion) {
      randomindex = Math.floor(Math.random() * questionList.length);
    }
    randomQuestion = questionList[randomindex];

    question.innerText = randomQuestion;
    question.classList.add("display");
    lastQuestion = randomindex;
  }, 1000);
});
